n1 = input("Digite algo: ")
print("O tipo primitivo é ",type(n1))
print("Tem espaço? ",n1.isspace())
print("È um número? ",n1.isnumeric())
print("È alfabético? ",n1.isalpha())
print("È alphanúmerico? ",n1.isalnum())
print("È maiúscula? ",n1.isupper())
print("È minúscula? ",n1.islower())
print("Ela está capitalizada? ",n1.istitle())
